SELECT * FROM BORROW
SELECT * FROM CUSTOMERS
UPDATE DEPOSIT SET AMOUNT=5000
WHERE AMOUNT=3000;

UPDATE BORROW SET BNAME='C.G. ROAD'
WHERE CNAME ='ANIL';

UPDATE DEPOSIT SET ACTNO=111,AMOUNT=5000
WHERE CNAME='SANDIP';

UPDATE BORROW SET AMOUNT=AMOUNT + (0.1* AMOUNT)

UPDATE DEPOSIT SET AMOUNT=5000
WHERE ACTNO>103 AND ACTNO<107;

UPDATE BORROW SET AMOUNT=NULL 
WHERE LOANNO=321;

UPDATE BORROW SET LOANNO=401,BNAME='AJNI'
WHERE LOANNO=201 AND BNAME='VRCE';

UPDATE CUSTOMERS SET CNAME='ANIL JAIN'
WHERE CNAME='ANIL';

UPDATE DEPOSIT SET CNAME='RAMESH',BNAME='VRCE',AMOUNT=5500
WHERE ACTNO=102;

UPDATE BORROW SET BNAME=NULL ,AMOUNT=NULL 
WHERE LOANNO=481 AND CNAME='KRANTI';

