CREATE TABLE STUDENT_WEB
(
StuID INT,
FirstName VARCHAR(25),
LastName VARCHAR(25),
Website VARCHAR(50),
City VARCHAR(25),
Division VARCHAR(20)
);

INSERT INTO STUDENT_WEB
VALUES
(1044 ,'Bhoomi',' Gajera',' checkyourmath.com ','Ahmedabad ','III-DCW'),
(1055 ,'Harmit',' Mitel',' NULL',' Rajkot',' II-BCY'),
(1066 ,'Ashok',' Jani',' NULL ','Baroda ','II-BCZ')

--1
SELECT *FROM STUDENT_WEB
WHERE FirstName LIKE 'K%'

--2
SELECT *FROM STUDENT_WEB
WHERE FirstName LIKE '_____'

--3
SELECT FirstName,LastName FROM STUDENT_WEB
WHERE City LIKE '_____A'

--4
SELECT *FROM STUDENT_WEB
WHERE LastName LIKE '%TEL'

--5
SELECT *FROM STUDENT_WEB
WHERE FirstName LIKE 'HA%T'

--6
SELECT *FROM STUDENT_WEB
WHERE FirstName LIKE 'K_Y%'

--7
SELECT *FROM STUDENT_WEB
WHERE FirstName LIKE '_____' AND Website IS NULL

--8
SELECT *FROM STUDENT_WEB
WHERE LastName LIKE '%JER%'

--9
SELECT *FROM STUDENT_WEB
WHERE City LIKE 'R%' OR City LIKE 'B%'

--10
SELECT *FROM STUDENT_WEB
WHERE Website IS NOT NULL

--11
SELECT *FROM STUDENT_WEB
WHERE FirstName LIKE '[A-H]%'

--12
SELECT *FROM STUDENT_WEB
WHERE FirstName LIKE '_[A,E,I,O,U]%'

--13
SELECT *FROM STUDENT_WEB
WHERE City LIKE '%ROD%'

--14
SELECT *FROM STUDENT_WEB
WHERE Website LIKE 'BI%'

--15
SELECT CITY FROM STUDENT_WEB
WHERE LastName LIKE '______'

--16
SELECT *FROM STUDENT_WEB
WHERE City LIKE '_____' AND City NOT LIKE 'BA%'

--17
SELECT *FROM STUDENT_WEB
WHERE Division LIKE 'II%'

--18
SELECT FirstName FROM STUDENT_WEB
WHERE Division LIKE '%BC%'

--19
SELECT StuID,City FROM STUDENT_WEB
WHERE Division LIKE '______'	AND Website IS NOT NULL

--20.

SELECT *FROM STUDENT_WEB
WHERE FirstName NOT LIKE '__[A,E,I,O,U]%'