SELECT * FROM STUDENT
SELECT * FROM EMPLOYEE
SELECT * FROM RESULT
--1. Combine information from student and result table using cross join or Cartesian product.
CREATE VIEW STUD_RESULT_1
AS SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM STUDENT S , RESULT R
SELECT * FROM STUD_RESULT_1

--2. Display Rno, Name, Branch and SPI of all students.
CREATE VIEW STUD_RESULT_2 
AS SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM STUDENT S FULL OUTER JOIN RESULT R
ON S.RNO=R.RNO
SELECT * FROM STUD_RESULT_2

--3. Display Rno, Name, Branch and SPI of CE branch’s student only.
CREATE VIEW STUD_RESULT_3 AS
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM STUDENT S LEFT OUTER JOIN RESULT R
ON S.RNO=R.RNO
WHERE BRANCH='CE';
SELECT * FROM STUD_RESULT_3

--4. Display Rno, Name, Branch and SPI of other than EC branch’s student only.
CREATE VIEW STUD_RESULT_4 AS 
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM STUDENT S LEFT OUTER JOIN RESULT R
ON S.RNO=R.RNO
WHERE BRANCH!='EC';
SELECT * FROM STUD_RESULT_4

--5. Display average result of each branch.
CREATE VIEW STUD_RESULT_5 AS
SELECT S.BRANCH,AVG(R.SPI) AS AVERAGE FROM STUDENT S LEFT OUTER JOIN RESULT R
ON S.RNO=R.RNO
GROUP BY S.BRANCH
SELECT * FROM STUD_RESULT_5

--6. Display average result of each branch and sort them in ascending order by SPI.
CREATE VIEW STUD_RESULT_6 AS 
SELECT S.BRANCH,AVG(R.SPI) AS SPI FROM STUDENT S LEFT OUTER JOIN RESULT R
ON S.RNO=R.RNO
GROUP BY S.BRANCH
ORDER BY AVG(R.SPI)
OFFSET 0 ROWS

OR 

CREATE VIEW STUD_RESULT_6 AS 
SELECT TOP 4 S.BRANCH,AVG(R.SPI) AS SPI FROM STUDENT S LEFT OUTER JOIN RESULT R
ON S.RNO=R.RNO
GROUP BY S.BRANCH
ORDER BY AVG(R.SPI)
SELECT * FROM STUD_RESULT_6

--7. Display average result of CE and ME branch. 
CREATE VIEW STUD_RESULT_7 AS 
SELECT S.BRANCH AS BRANCH,AVG(R.SPI) AS SPI FROM STUDENT S LEFT OUTER JOIN RESULT R
ON S.RNO=R.RNO
WHERE BRANCH='CE' OR BRANCH='ME'
GROUP BY S.BRANCH
SELECT * FROM STUD_RESULT_7

--8. Perform the left outer join on Student and Result tables.
CREATE VIEW STUD_RESULT_8 AS 
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM STUDENT S LEFT OUTER JOIN RESULT R
ON S.RNO=R.RNO
SELECT * FROM STUD_RESULT_8

--9. Perform the right outer join on Student and Result tables.
CREATE VIEW STUDE_RESULT_9 AS 
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM STUDENT S RIGHT OUTER JOIN RESULT R
ON S.RNO=R.RNO
SELECT * FROM STUDE_RESULT_9

--10. Perform the full outer join on Student and Result tables. 
CREATE VIEW STUDE_RESULT_10 AS 
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI FROM STUDENT S FULL OUTER JOIN RESULT R
ON S.RNO=R.RNO
SELECT * FROM STUDE_RESULT_10

--11. Retrieve the names of employee along with their manager name from the Employee table.
CREATE VIEW STUD_RESULT_11 AS 
SELECT M.NAME AS MANAGER, E.NAME AS EMPLOYEE FROM EMPLOYEE M LEFT OUTER JOIN EMPLOYEE E
ON M.MANAGERNO= E.EMPLOYEENO 
SELECT * FROM STUD_RESULT_11



 